name: Hourly uptime check

on:
  schedule:
    # Runs every hour at minute 0 UTC
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3

      - name: 🌐 Check target status
        id: http
        run: |
          TARGET=$(jq -r .target status.json)
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$TARGET")
          echo "status=$STATUS" >> $GITHUB_OUTPUT

      - name: ⚙️ Update status.json with jq
        run: |
          STATUS=${{ steps.http.outputs.status }}
          HOURS=$(jq '.hoursUp // 0' status.json)
          if [ "$STATUS" = "200" ]; then
            HOURS=$((HOURS + 1))
          else
            HOURS=0
          fi
          DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          jq --arg hours "$HOURS" --arg lastChecked "$DATE" \
             '.hoursUp = ($hours|tonumber) | .lastChecked = $lastChecked' \
             status.json > status.tmp.json
          mv status.tmp.json status.json

      - name: ✏️ Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add status.json
            git commit -m "chore: hourly uptime update"
            git push
          else
            echo "No changes to commit"
          fi
