name: Uptime check every 5 minutes

on:
  schedule:
    # Runs every 5 minutes UTC
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: 🌐 Check target status with timeout
        id: http
        run: |
          TARGET=$(jq -r .target status.json)
          # Curl with 30s timeout; on timeout or error, treat as failure (000)
          HTTP=$(curl -L --max-time 30 -s -o /dev/null -w "%{http_code}" "$TARGET" || echo '000')
          echo "status=$HTTP" >> $GITHUB_OUTPUT

      - name: ⚙️ Update uptime files
        run: |
          STATUS=${{ steps.http.outputs.status }}
          HOURS=$(jq '.hoursUp // 0' status.json)
          IS_UP=false

          if [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 400 ]; then
            # Site still up → increment counter
            HOURS=$((HOURS + 1))
            IS_UP=true
          else
            # Site down → record completed uptime if > 0
            if [ "$HOURS" -gt 0 ]; then
              DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
              SECONDS=$((HOURS * 3600))
              jq --arg seconds "$SECONDS" --arg lastChecked "$DATE" \
                '. += [ { seconds: ($seconds|tonumber), lastChecked: $lastChecked } ]' \
                history.json > history.tmp.json
              mv history.tmp.json history.json
            fi
            # Reset counter and mark down
            HOURS=0
            IS_UP=false
          fi

          # Always update status.json with new hoursUp, isUp & timestamp
          NOW=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          jq --arg hours "$HOURS" --arg lastChecked "$NOW" --argjson isUp $IS_UP \
            '.hoursUp = ($hours|tonumber) |
             .lastChecked = $lastChecked |
             .isUp = $isUp' \
            status.json > status.tmp.json
          mv status.tmp.json status.json

      - name: ✏️ Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [[ -n "$(git status --porcelain)" ]]; then
            git add status.json history.json
            git commit -m "chore: uptime update"
            git push
          else
            echo "No changes to commit"
          fi
